### PR TITLE
Remove defaults from button theme & update border merge 

### PR DESCRIPTION
**Pull request by dickermoshe**
Closes https://github.com/nank1ro/flutter-shadcn-ui/issues/184

### CODE REVIEW

**Comment by nank1ro** [comment]
There is something wrong with your PR.
I ran the example, opened the Accordion page and it throws:
```dart
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building ShadDecorator(dirty, dependencies:
[ShadInheritedTheme]):
'package:shadcn_ui/src/theme/components/decorator.dart': Failed assertion: line 138 pos 12:
'BorderSide.canMerge(top, other.top)': is not true.

The relevant error-causing widget was:
  ShadDecorator
  ShadDecorator:file:///Users/ale/github/flutter-shadcn-ui/lib/src/components/switch.dart:174:22

When the exception was thrown, this was the stack:
#2      ShadBorder.mergeWith (package:shadcn_ui/src/theme/components/decorator.dart:138:12)
#3      ShadDecoration.mergeWith (package:shadcn_ui/src/theme/components/decorator.dart:303:35)
```

**Comment by nank1ro** [comment]
Are you sure the `BorderSide.canMerge` is needed?
Seems like something the Flutter team decided but I don't understand the reason.
```dart
/// Two sides can be merged if one or both are zero-width with
/// [BorderStyle.none], or if they both have the same color and style.
```
I want shadcn_ui to allow every kind of customizations, and not limit for the same style or color.

**Comment by dickermoshe** [comment]
Forgive me, I misunderstood what `BorderSide.merge` does. Turns out it's a pretty badly named function.
That function adds the 2 borders, instead of merging them.

Turns out you can't merge `Borders`, so defining one completely overwrites the previous one, even if you just want to change the color.

Gonna remove the changes and just keep the button stuff. Sounds Good?

**Comment by nank1ro** [comment]
Sounds good 👍

**Comment by dickermoshe** [comment]
done.

**Review by nank1ro — APPROVED** [review]

**Pull request merged**
