### PR TITLE
Playground

### PR DESCRIPTION
**Pull request by dickermoshe**
If you aren't interested in this let me know.

### CODE REVIEW

**Comment by nank1ro** [comment]
Do you mean using https://www.widgetbook.io to render widgets and change their properties from the right panel?

**Comment by dickermoshe** [comment]
Yes, It would help showcase the widgets in a clearer way than the docs site.
Like this:
https://flutter.moon.io

**Comment by nank1ro** [comment]
I know WidgetBook and I already used it.
I think that the docs site is better as it is, because in the future, in addition to simply seeing the widget with the code, there may be real documentation.
The purpose of WidgetBook is simply to display the widget and to change its properties from the UI.
It's a good idea, but it should be put somewhere else, perhaps at `/shadcn-ui/playground` or something like that.
The point is that it does not replace the documentation.

**Comment by dickermoshe** [comment]
I agree.
I’m realizing now that widgetbook isn’t for this.
Forking the flex playground and removing all the material stuff would be
much more helpful.
I don’t know how much work that would entail, I’ll investigate.

**Pull request closed without merging**
