### PR TITLE
feat: added text selection menu

### PR DESCRIPTION
**Pull request by moshOntong-IT**
Issue related https://github.com/nank1ro/flutter-shadcn-ui/issues/139

### CODE REVIEW

**Review by nank1ro — COMMENTED** [review]
Why do you renamed variables?
1. You don't need to use _variable because we are in a private state _State.
2. I'm using private var when I initialize the same object to differentiate between the internal and external ones.

3. Don't you think we need a custom toolbar? The material one is a bit ugly

**Comment by moshOntong-IT** [comment]
> Why do you renamed variables?
> 1. You don't need to use _variable because we are in a private state _State.
> 2. I'm using private var when I initialize the same object to differentiate between the internal and external ones.
> 
> 3. Don't you think we need a custom toolbar? The material one is a bit ugly

I renamed it into have prefix word 'effective' similar to effectiveGap within build method. Maybe I can remove those being private variables😅

**Comment by moshOntong-IT** [comment]
> Why do you renamed variables?
> 1. You don't need to use _variable because we are in a private state _State.
> 2. I'm using private var when I initialize the same object to differentiate between the internal and external ones.
> 
> 3. Don't you think we need a custom toolbar? The material one is a bit ugly

About number 3, I am also thinking about that. Maybe we can provide a default toolbar that is based on Shadcn design, what do you think?

**Comment by nank1ro** [comment]
> About number 3, I am also thinking about that. Maybe we can provide a default toolbar that is based on Shadcn design, what do you think?

Yes, I don't know if customizing it from the ThemeData is enough or we need a custom implementation

**Comment by moshOntong-IT** [comment]
> > About number 3, I am also thinking about that. Maybe we can provide a default toolbar that is based on Shadcn design, what do you think?
> 
> Yes, I don't know if customizing it from the ThemeData is enough or we need a custom implementation

For now, the toolbar is an Adaptive for difference platform. 

For Windows:

image

For Android:
image

For Web:
image


If this case can be our default. And then we can provide a Custom ShadInputToolbar then.

**Comment by nank1ro** [comment]
Can you check what is customizable from the material themedata?
I'm interested in the colors and shadows

**Comment by moshOntong-IT** [comment]
> Can you check what is customizable from the material themedata? I'm interested in the colors and shadows

Alright, will do

**Comment by moshOntong-IT** [comment]
```

class _TextSelectionToolbarOverflowable extends StatefulWidget {
  const _TextSelectionToolbarOverflowable({
    required this.isAbove,
    required this.toolbarBuilder,
    required this.children,
  }) : assert(children.length > 0);

  final List<Widget> children;

  // When true, the toolbar fits above its anchor and will be positioned there.
  final bool isAbove;

  // Builds the toolbar that will be populated with the children and fit inside
  // of the layout that adjusts to overflow.
  final ToolbarBuilder toolbarBuilder;

  @override
  _TextSelectionToolbarOverflowableState createState() => _TextSelectionToolbarOverflowableState();
}

class _TextSelectionToolbarOverflowableState extends State<_TextSelectionToolbarOverflowable> with TickerProviderStateMixin {
  // Whether or not the overflow menu is open. When it is closed, the menu
  // items that don't overflow are shown. When it is open, only the overflowing
  // menu items are shown.
  bool _overflowOpen = false;

  // The key for _TextSelectionToolbarTrailingEdgeAlign.
  UniqueKey _containerKey = UniqueKey();

  // Close the menu and reset layout calculations, as in when the menu has
  // changed and saved values are no longer relevant. This should be called in
  // setState or another context where a rebuild is happening.
  void _reset() {
    // Change _TextSelectionToolbarTrailingEdgeAlign's key when the menu changes
    // in order to cause it to rebuild. This lets it recalculate its
    // saved width for the new set of children, and it prevents AnimatedSize
    // from animating the size change.
    _containerKey = UniqueKey();
    // If the menu items change, make sure the overflow menu is closed. This
    // prevents getting into a broken state where _overflowOpen is true when
    // there are not enough children to cause overflow.
    _overflowOpen = false;
  }

  @override
  void didUpdateWidget(_TextSelectionToolbarOverflowable oldWidget) {
    super.didUpdateWidget(oldWidget);
    // If the children are changing at all, the current page should be reset.
    if (!listEquals(widget.children, oldWidget.children)) {
      _reset();
    }
  }

  @override
  Widget build(BuildContext context) {
    assert(debugCheckHasMaterialLocalizations(context));
    final MaterialLocalizations localizations = MaterialLocalizations.of(context);

    return _TextSelectionToolbarTrailingEdgeAlign(
      key: _containerKey,
      overflowOpen: _overflowOpen,
      textDirection: Directionality.of(context),
      child: AnimatedSize(
        // This duration was eyeballed on a Pixel 2 emulator running Android
        // API 28.
        duration: const Duration(milliseconds: 140),
        child: widget.toolbarBuilder(context, _TextSelectionToolbarItemsLayout(
          isAbove: widget.isAbove,
          overflowOpen: _overflowOpen,
          children: <Widget>[
            // TODO(justinmc): This overflow button should have its own slot in
            // _TextSelectionToolbarItemsLayout separate from children, similar
            // to how it's done in Cupertino's text selection menu.
            // https://github.com/flutter/flutter/issues/69908
            // The navButton that shows and hides the overflow menu is the
            // first child.
            _TextSelectionToolbarOverflowButton(
              icon: Icon(_overflowOpen ? Icons.arrow_back : Icons.more_vert),
              onPressed: () {
                setState(() {
                  _overflowOpen = !_overflowOpen;
                });
              },
              tooltip: _overflowOpen
                  ? localizations.backButtonTooltip
                  : localizations.moreButtonTooltip,
            ),
            ...widget.children,
          ],
        )),
      ),
    );
  }
}
```

```
class _TextSelectionToolbarOverflowButton extends StatelessWidget {
  const _TextSelectionToolbarOverflowButton({
    required this.icon,
    this.onPressed,
    this.tooltip,
  });

  final Icon icon;
  final VoidCallback? onPressed;
  final String? tooltip;

  @override
  Widget build(BuildContext context) {
    return Material(
      type: MaterialType.card,
      color: const Color(0x00000000),
      child: IconButton(
        // TODO(justinmc): This should be an AnimatedIcon, but
        // AnimatedIcons doesn't yet support arrow_back to more_vert.
        // https://github.com/flutter/flutter/issues/51209
        icon: icon,
        onPressed: onPressed,
        tooltip: tooltip,
      ),
    );
  }
}
```

**Comment by moshOntong-IT** [comment]
This is on android toolbar based

**Review by nank1ro — APPROVED** [review]

**Pull request merged**
